name: micro-service-platform

services:
  kafka:
    image: bitnamilegacy/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      # chế độ đơn giản (single node).
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    restart: on-failure

  mysql-identity:
    image: mysql:8.0.36-debian
    container_name: mysql-db
    hostname: mysql-identity
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      # Image MySQL sẽ tự động tạo database này trong lần khởi động đầu tiên.
      MYSQL_DATABASE: "social_platform_identity"
    volumes:
      - identity-db-data:/var/lib/mysql
    healthcheck:
      # Docker sẽ liên tục chạy lệnh này bên trong container để kiểm tra.
      # Lệnh `mysqladmin ping` chỉ thành công khi MySQL server đã thực sự sẵn sàng nhận kết nối.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s # Mỗi 10 giây kiểm tra một lần.
      timeout: 5s   # Chờ tối đa 5 giây cho mỗi lần kiểm tra.
      retries: 10   # Thử lại 10 lần trước khi báo lỗi.
    restart: on-failure

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    hostname: identity-service
    ports:
      - "8080:8080"
    # ĐIỀU KIỆN CHỜ NÂNG CAO:
    depends_on:
      mysql-identity:
        # chờ cho đến khi healthcheck của mysql-identity báo trạng thái healthy.
        # điều này đảm bảo identity-service sẽ không bao giờ bị lỗi connection refused".
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-identity:3306/social_platform_identity
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APP_SERVICES_PROFILE=http://profile-service:8081/profile
    restart: on-failure

  neo4j-profile:
    image: neo4j:4.4
    container_name: neo4j-profile
    hostname: neo4j-profile
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/12345678
    volumes:
      - profile-db-data:/data
    restart: on-failure

  profile-service:
    build:
      context: ./profile-service
    container_name: profile-service
    hostname: profile-service
    ports:
      - "8081:8081"
    depends_on:
      - neo4j-profile
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j-profile:7687
      - APP_SERVICES_FILE=http://file-service:8084
    restart: on-failure

  mongo-db:
    image: bitnamilegacy/mongodb:7.0
    container_name: mongo-db
    hostname: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/data/db
    restart: on-failure

  post-service:
    build:
      context: ./post-service
    container_name: post-service
    hostname: post-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo-db
      - profile-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo-db:27017/post-service?authSource=admin
      - APP_SERVICES_PROFILE_URL=http://profile-service:8081/profile
    restart: on-failure

  file-service:
    build:
      context: ./file-service
    container_name: file-service
    hostname: file-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo-db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo-db:27017/file-service?authSource=admin
      - APP_FILE_STORAGE-DIR=/upload
    volumes:
      - file-storage:/upload
    restart: on-failure

  chat-service:
    build:
      context: ./chat-service
    container_name: chat-service
    hostname: chat-service
    ports:
      - "8085:8085"
    depends_on:
      - mongo-db
      - profile-service
      - identity-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo-db:27017/chat-service?authSource=admin
      - APP_SERVICES_PROFILE_URL=http://profile-service:8081/profile
      - APP_SERVICES_IDENTITY_URL=http://identity-service:8080/identity
    restart: on-failure

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    hostname: notification-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo-db
      - kafka
    # Đọc file .env từ thư mục gốc.
    env_file:
      - ./.env
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo-db:27017/notification-service?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: on-failure

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    hostname: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - identity-service
      - profile-service
      - notification-service
      - post-service
      - file-service
      - chat-service
    # Ghi đè các route để trỏ đến tên hostname của các service trong mạng Docker.
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_ID=identity_service
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://identity-service:8080
    restart: on-failure

volumes:
  identity-db-data:
  profile-db-data:
  mongodb-data:
  file-storage:
