server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
#            stripPrefix = 2 là để match với /api/v1
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
#           chỉ cho phép truy cập prefix user còn prefix internal/user thì không
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-pre fix}/notification/**
          filters:
            - StripPrefix=2
