server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2

        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2

        - id: file_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2

        # Route cho các REST API của chat-service
        - id: chat_service_http
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/chat/conversations/**, ${app.api-prefix}/chat/messages/**
          filters:
            - StripPrefix=2

        # Route MỚI cho kết nối WebSocket của chat-service
        - id: chat_service_websocket
          uri: ws://localhost:8085
          predicates:
            - Path=${app.api-prefix}/chat/socket.io/**
